# Generated by Django 4.1.6 on 2023-02-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='can_call',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='can_email',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='can_mobil_notification',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='can_sms',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='isESP',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
