# Generated by Django 4.1.6 on 2023-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.CharField(choices=[('text-primary', 'primary'), ('text-secondary', 'secondary'), ('text-success', 'success'), ('text-danger', 'danger'), ('text-warning', 'warning'), ('text-info', 'info'), ('text-light', 'light'), ('text-dark', 'dark'), ('text-muted', 'muted'), ('text-white', 'white')], max_length=15)),
                ('icon', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.CharField(choices=[('text-primary', 'primary'), ('text-secondary', 'secondary'), ('text-success', 'success'), ('text-danger', 'danger'), ('text-warning', 'warning'), ('text-info', 'info'), ('text-light', 'light'), ('text-dark', 'dark'), ('text-muted', 'muted'), ('text-white', 'white')], max_length=15)),
                ('icon', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='SocialMedia',
            field=models.ManyToManyField(blank=True, default=None, to='Account.socialmedia'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='talent',
            field=models.ManyToManyField(blank=True, default=None, to='Account.talent'),
        ),
    ]
