# Generated by Django 4.1.6 on 2023-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_socialmedia_talent_customusermodel_socialmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
