# Generated by Django 4.1.6 on 2023-02-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_socialmedia_priority_talent_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='color',
            field=models.CharField(choices=[(' ', 'None'), ('text-primary', 'primary'), ('text-secondary', 'secondary'), ('text-success', 'success'), ('text-danger', 'danger'), ('text-warning', 'warning'), ('text-info', 'info'), ('text-light', 'light'), ('text-dark', 'dark'), ('text-muted', 'muted'), ('text-white', 'white'), ('link-primary', 'l-primary'), ('link-secondary', 'l-secondary'), ('link-success', 'l-success'), ('link-danger', 'l-danger'), ('link-warning', 'l-warning'), ('link-info', 'l-info'), ('link-light', 'l-light'), ('link-dark', 'l-dark'), ('link-muted', 'l-muted'), ('link-white', 'l-white')], max_length=15),
        ),
        migrations.AlterField(
            model_name='talent',
            name='color',
            field=models.CharField(choices=[(' ', 'None'), ('text-primary', 'primary'), ('text-secondary', 'secondary'), ('text-success', 'success'), ('text-danger', 'danger'), ('text-warning', 'warning'), ('text-info', 'info'), ('text-light', 'light'), ('text-dark', 'dark'), ('text-muted', 'muted'), ('text-white', 'white'), ('link-primary', 'l-primary'), ('link-secondary', 'l-secondary'), ('link-success', 'l-success'), ('link-danger', 'l-danger'), ('link-warning', 'l-warning'), ('link-info', 'l-info'), ('link-light', 'l-light'), ('link-dark', 'l-dark'), ('link-muted', 'l-muted'), ('link-white', 'l-white')], max_length=15),
        ),
    ]
