# Generated by Django 4.1.6 on 2023-08-17 05:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmodel',
            name='md',
            field=mdeditor.fields.MDTextField(default=0),
            preserve_default=False,
        ),
    ]
