# Generated by Django 4.2.4 on 2023-08-20 06:45

import autoslug.fields
from django.db import migrations, models
import django.utils.text
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmap', '0002_roadmapmodel_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name', slugify=django.utils.text.slugify),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadmapmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
