# Generated by Django 4.2.4 on 2023-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gamepage'),
        ('Roadmap', '0004_roadmapmodel_can_share_alter_roadmapmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmodel',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
    ]
