# Generated by Django 4.2.4 on 2023-08-20 08:28

import autoslug.fields
from django.db import migrations
import django.utils.text


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmap', '0006_alter_roadmapmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=django.utils.text.slugify),
        ),
    ]
