# Generated by Django 4.1.6 on 2023-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('explanation', models.TextField()),
                ('github_url', models.URLField(default='https://github.com/F4ruk-seker')),
                ('technologies', models.ManyToManyField(to='projects.technologies')),
            ],
        ),
    ]
