# Generated by Django 4.1.6 on 2023-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=None, upload_to='projects'),
            preserve_default=False,
        ),
    ]
