# Generated by Django 4.1.6 on 2023-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
