# Generated by Django 4.1.6 on 2023-02-04 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_technologies_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
