# Generated by Django 4.2.4 on 2023-08-22 05:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_detailed_explanation_projects_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='detailed_explanation',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
