# Generated by Django 4.1.6 on 2023-02-06 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(choices=[('Business', 'business'), ('Freelance ', 'Freelance '), ('Help', 'Help'), ('Other', 'Other')], max_length=15)),
                ('message', models.TextField(max_length=1000)),
                ('sender_detail', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
