# Generated by Django 4.2.4 on 2023-08-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTypeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default=None, null=True)),
                ('icon', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, null=True)),
                ('description', models.TextField()),
                ('video_length', models.IntegerField()),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('thumbnail', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('length', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('game_type', models.ManyToManyField(to='Game.gametypemodels')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.gameinfomodel', verbose_name='game_info')),
                ('songs', models.ManyToManyField(to='Game.musicinfomodel')),
                ('tags', models.ManyToManyField(to='Game.gametypemodels')),
                ('video', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.gamevideomodel', verbose_name='game_video')),
            ],
        ),
    ]
