# Generated by Django 4.2.4 on 2023-08-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('pin', models.BooleanField(default=False)),
                ('info', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.gameinfomodel')),
                ('songs', models.ManyToManyField(default=None, null=True, to='Game.musicinfomodel')),
                ('tags', models.ManyToManyField(default=None, null=True, to='Game.gametypemodels')),
                ('video', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.gamevideomodel')),
            ],
        ),
    ]
