# Generated by Django 4.2.4 on 2023-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_alter_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id',
            new_name='uuid',
        ),
    ]
