# Generated by Django 4.2.4 on 2023-08-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='songs',
            field=models.ManyToManyField(to='Game.musicinfomodel'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='Game.gametypemodels'),
        ),
    ]
