# Generated by Django 4.2.4 on 2023-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_alter_game_songs_alter_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfomodel',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
