# Generated by Django 4.2.4 on 2023-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_alter_musicinfomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicinfomodel',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
