# Generated by Django 4.2.4 on 2023-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_game_view_alter_gamevideomodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideomodel',
            name='video_length',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='musicinfomodel',
            name='length',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
