# Generated by Django 4.2.4 on 2023-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_musicinfomodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfomodel',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='musicinfomodel',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='musicinfomodel',
            name='length',
            field=models.TimeField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='musicinfomodel',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='musicinfomodel',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
