# Generated by Django 4.2.4 on 2023-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_alter_musicinfomodel_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevideomodel',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
