# Generated by Django 4.2.4 on 2023-08-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_gamevideomodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevideomodel',
            name='thumbnail',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
