# Generated by Django 4.1.6 on 2023-02-05 07:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_projects_image_projects_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('view', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(null=True)),
                ('robots', models.TextField(null=True)),
                ('canonical', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('image_alt', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CvPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('view', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(null=True)),
                ('robots', models.TextField(null=True)),
                ('canonical', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('image_alt', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('view', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(null=True)),
                ('robots', models.TextField(null=True)),
                ('canonical', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('image_alt', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('view', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(null=True)),
                ('robots', models.TextField(null=True)),
                ('canonical', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('image_alt', models.TextField(null=True)),
                ('top_3_projects', models.ManyToManyField(blank=True, to='projects.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
