# Generated by Django 4.1.6 on 2023-02-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_blogpage_image_alter_cvpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='cvpage',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='canonical',
        ),
    ]
