# Generated by Django 4.2.4 on 2023-08-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_mainpage_road_map_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='road_map_handle',
            new_name='road_map',
        ),
    ]
