# Generated by Django 4.1.6 on 2023-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_blogpage_canonical_remove_cvpage_canonical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='view',
        ),
        migrations.RemoveField(
            model_name='cvpage',
            name='view',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='view',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='view',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='base.viewmodel'),
        ),
        migrations.AddField(
            model_name='cvpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='base.viewmodel'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='base.viewmodel'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='base.viewmodel'),
        ),
    ]
