# Generated by Django 4.2.4 on 2023-08-19 07:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_road_map_handle_mainpage_road_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(null=True)),
                ('robots', models.TextField(null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.TextField(null=True)),
                ('view', models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
