# Generated by Django 4.1.6 on 2023-03-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_viewmodel_remove_blogpage_view_remove_cvpage_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='visit_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
