# Generated by Django 4.1.6 on 2023-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_viewmodel_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
