# Generated by Django 4.1.6 on 2023-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_viewmodel_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='cvpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='base.viewmodel'),
        ),
    ]
