# Generated by Django 4.2.4 on 2023-08-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_fakeadminloginpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminloginpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='adminloginpage',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='adminloginpage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='adminloginpage',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='fakeadminloginpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fakeadminloginpage',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='fakeadminloginpage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='fakeadminloginpage',
            name='robots',
        ),
    ]
