# Generated by Django 4.1.6 on 2023-03-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_blogpage_view_alter_cvpage_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='cvpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
    ]
