# Generated by Django 4.1.6 on 2023-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_blogpage_view_alter_cvpage_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmodel',
            name='is_i_am',
            field=models.BooleanField(default=False),
        ),
    ]
