# Generated by Django 4.2.4 on 2023-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_viewmodel_ip_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewmodel',
            name='ip_query_id',
        ),
        migrations.AddField(
            model_name='viewmodel',
            name='ip_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
