# Generated by Django 4.2.4 on 2023-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_viewmodel_ip_query_id_viewmodel_ip_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='ip_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
