# Generated by Django 4.2.4 on 2023-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_viewmodel_ip_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmodel',
            name='user_agent',
            field=models.TextField(blank=True, default=None, editable=False, null=True),
        ),
    ]
