# Generated by Django 4.2.4 on 2023-09-25 15:03

import base.models.view
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_viewmodel_ip_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='ip_data',
            field=models.JSONField(blank=True, default=base.models.view.default_ip_data, null=True),
        ),
    ]
