# Generated by Django 4.1.6 on 2023-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_otpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdevice',
            name='hash_gen',
            field=models.TextField(max_length=50),
        ),
    ]
