# Generated by Django 4.2.4 on 2023-12-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_viewmodel_ip_data'),
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='base.viewmodel'),
        ),
    ]
